### ISSUE TITLE
rilidar initialization

### ISSUE THREAD

**Issue by Marco-Andarcia** [yujinrobot/rplidar_ros#1]
The timeout for initialization of rplidar needs to be increased.
When running gopher_meta minimal_w_jyop if battery is low (or unpluggled as we tested) rplidar initialization times out and the topic doesn't post any data.

**Comment by stonier** [comment]
Added better logging in 84cbfc45.

Played around with the gocart skeleton last night...rplidar is not even working there, on its own.
- Creates driver ........OK
- Connects ..............OK
- Gets health status............OK (note, this is a request/response behaviour)
- Start/stop motors on ros services.........OK
- Start Scanning............OK (apparently)
- Get scan data..........TIMEOUT (boooooooooooooo)

**Comment by Marco-Andarcia** [comment]
I tried by it's own and it was giving me data at 7.9 Hz or something like
that. I will take a look at it.

On Sun, Aug 2, 2015 at 8:44 PM, Daniel Stonier notifications@github.com
wrote:

> Added better logging in 84cbfc4
> https://github.com/yujinrobot/rplidar_ros/commit/84cbfc45ebb1edf722759d51ee13e7f0cf6d41cf
> .
> 
> Played around with the gocart skeleton last night...rplidar is not even
> working there, on its own.
> - Creates driver ........OK
> - Connects ..............OK
> - Gets health status............OK (note, this is a request/response
>   behaviour)
> - Start/stop motors on ros services.........OK
> - Start Scanning............OK (apparently)
> - Get scan data..........TIMEOUT (boooooooooooooo)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yujinrobot/rplidar_ros/issues/1#issuecomment-127019504
> .

## 

_Marco Andarcia._
*Controls Software Engineer. *

**Comment by bit-pirate** [comment]
Closing this. We have improved the (re-)initialisation significantly and there haven't been new reports on this issue.
