### ISSUE TITLE
Parallel branch[master] for upstream

### ISSUE THREAD

**Issue by naveedhd** [yujinrobot/rplidar_ros#19]
I have made up a branch named `master` which tracks only the sdk changes that we want to push upstream and as a reference of sdk for our custom branches.

As was discussed to have sdk and extras separate, but since the way library is bundled, it is possible to keep things separate by branches.

**Comment by naveedhd** [comment]
@stonier we can start by a pull request with minimal differences in sdk. i.e. `drv = NULL;`.

**Comment by stonier** [comment]
Let's track what we send/plan to send upstream over in #22.

**Comment by stonier** [comment]
Close this one?
