### ISSUE TITLE
gocart_21 branch as primary

### ISSUE THREAD

**Issue by naveedhd** [yujinrobot/rplidar_ros#20]
Can we make `[gocart_21]` branch as primary branch so that it gets tested with binaries with 2.0s?

**Comment by stonier** [comment]
I was hoping to move to that `rplidar_sdk` and `rplidar_nodelet` package structure for both 2.0 and 2.1

**Comment by naveedhd** [comment]
On it!

**Comment by stonier** [comment]
Getting my head around the current situation...

Assumptions: `gocart_21` is being targeted as the branch we will use _actively_ for providing the sdk and headers. 

If this is true, then:
- Drop the last commit, ce1e6ca2. It has all of our nodelet changes as well and we don't want them. The only commits on top should be exactly those we try to push upstream.
- Create a commit(s) which makes our minor changes (e.g. drv to NULL).
- Create a commit which installs and exports sdk headers/libs
- Is there anything else to do (see #22)?
- Create our nodelet package as per [rplidar_extras#1](https://github.com/yujinrobot/rplidar_extras/issues/1)
- Do the testing

Finally confirm with me and then we can:
- Rename the current `devel` to `graveyard/2.0` (as a just in case)
- Rename this branch to `devel`
- Add the new `rplidar_extras` to the groot source workspaces
- Be happy!
- .. and slowly try to get our sdk changes in upstream

**Comment by naveedhd** [comment]
_that_ branch is `master`! So to summarise:
- `devel` -> (stable sdk + nodelet)
- `gocart_21` -> (latest sdk + nodelet)
- `master` -> (sdk only for upstreaming)

This branch is there if any of the gocart has new rplidar. This was planned earlier for testing with rplidar ears which didn't happen. I made this issue incase we need to test new sdk with current rplidars.

**Comment by naveedhd** [comment]
current structure:

* devel (default) -> (latest sdk with few changes to upstream's master)
* [rplidar_extras](https://github.com/yujinrobot/rplidar_extras) -> migrated nodelet
* graveyard/devel -> (older stable sdk + nodelet)
