### ISSUE TITLE
RPlidar burst!

### ISSUE THREAD

**Issue by stonier** [yujinrobot/rplidar_ros#5]
```
[ WARN] [1461155288.335518420]: RPLidar : Publishing Invalid data; might burst! watch out..
[ WARN] [1461155288.335636631]: RPLidar : Node count is not equal to 360
[ WARN] [1461155288.335677183]: Node Count: 1
[ WARN] [1461155288.335721848]: RPLidar : Time increment is infinity!
[ WARN] [1461155288.335751098]: Node Count: 1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Time is out of dual 32-bit range
[navi/move_base-36] process has died [pid 27903, exit code -6, cmd /opt/yujin/amd64/indigo-devel/lib/move_base/move_base /move_base/honk:=/gopher/commands/honk local_planner/future_odom:=/gopher/trajectory_controller/future_odom trajectory_control_end_time:=/gopher/trajectory_controller/trajectory_control_end_time cmd_vel:=/navi/commands/velocity /move_base/clear_and_rotate/cmd_vel:=/gopher/yocs_cmd_vel_mux/input/teleop odom:=/gopher/odom /move_base/clear_and_rotate/bumper:=/gopher/events/bumper __name:=move_base __log:=/home/yujin/.ros/log/4c92fc0c-06ed-11e6-9937-d0509978a29e/navi-move_base-36.log].
log file: /home/yujin/.ros/log/4c92fc0c-06ed-11e6-9937-d0509978a29e/navi-move_base-36*.log
```

**Comment by bit-pirate** [comment]
Awesome! Looks like it's time to get the fix in. Maybe we should leave a warning/info message saying when the driver discards scans.

**Comment by naveedhd** [comment]
There is also the case when there is invalid data and node count is less than 360 (more than 300) but not 1. It does not cause the crash. 

Should we drop it also? (not sure if the data is useful or not)

**Comment by stonier** [comment]
> Maybe we should leave a warning/info message

Definitely

> Should we drop it also? (not sure if the data is useful or not)

Sounds like you have to find out what that data looks like then. Do the laser scans pass on the reduced count? And if they do, they won't represent a full 360 degrees. I suspect that the data will be misrepresentative.

Q) What does the 1 actually mean in real world terms? I'm happy we can avoid the crash, but I would like to know the root cause, can you shed some light Naveed?

**Comment by naveedhd** [comment]
From the driver scan routine, it seems like it aborts scanning as soon as it hits some error, resulting in invalid data. I think 1 would mean the scan routine encounters error at the beginning of putting the device into scan and special case as compared to other cases where count is less than 360. But for that we would have to look inside the driver.

I assume the data less than 360 degrees is corrupt and at most can represent correct data less but than 2pi. If not occuring too frequently, dropping it is the safe choice, as it would mess up with scan splitter(maybe).

**Comment by stonier** [comment]
> I assume the data less than 360 degrees is corrupt and at most can represent correct data less but than 2pi. If not occuring too frequently, dropping it is the safe choice, as it would mess up with scan splitter(maybe).

+1 let's do it.

**Comment by naveedhd** [comment]
[PR here](https://github.com/yujinrobot/rplidar_ros/pull/7)
