### ISSUE TITLE
Merge nodelet upstream

### ISSUE THREAD

**Issue by jvgomez** [yujinrobot/rplidar_ros#8]
Hi, I think the contributions you did to this code are useful (specially the nodelet version of the driver). Are you guys planning to contribute it upstream? Or is there something that is specific for your robots?

**Comment by stonier** [comment]
Would like to, and we were originally pushing everything upstream. They were quite slow on catching PR's though, and we had changes piling up, so we need to de-spaghettifi things and hope they move faster on PR's. 

Just need to find a window in which our intern can sort this out, but that won't be for a month at least. Feel free to use this repo or pull the commit(s) and upstream it yourself in the meantime.

Just to note...the bugfix in f30f22505 is probably the most important one. Occasionally the assumption that the device sends 360 pieces of data breaks, and without that, the node will regularly crash and burn.

**Comment by jvgomez** [comment]
Thanks for the quick reply! Yeah, I saw that they seem to be slow checking the PRs. For sure I will use your code in the meanwhile, thanks!  (I guess we can close the issue).
